INSERT INTO states (id, title, letter, iso, slug, population) VALUES (1, 'Acre', 'AC', 12, 'acre', 816687);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (2, 'Alagoas', 'AL', 27, 'alagoas', 3358963);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (3, 'Amazonas', 'AM', 13, 'amazonas', 4001667);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (4, 'Amapá', 'AP', 16, 'amapa', 782295);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (5, 'Bahia', 'BA', 29, 'bahia', 15276566);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (6, 'Ceará', 'CE', 23, 'ceara', 8963663);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (7, 'Distrito Federal', 'DF', 53, 'distrito-federal', 2977216);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (8, 'Espírito Santo', 'ES', 32, 'espirito-santo', 3973697);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (9, 'Goiás', 'GO', 52, 'goias', 6695855);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (10, 'Maranhão', 'MA', 21, 'maranhao', 6954036);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (11, 'Minas Gerais', 'MG', 31, 'minas-gerais', 20997560);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (12, 'Mato Grosso do Sul', 'MS', 50, 'mato-grosso-do-sul', 2682386);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (13, 'Mato Grosso', 'MT', 51, 'mato-grosso', 3305531);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (14, 'Pará', 'PA', 15, 'para', 8272724);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (15, 'Paraiba', 'PB', 25, 'paraiba', 3999415);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (16, 'Pernambuco', 'PE', 26, 'pernambuco', 9410336);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (17, 'Piauí', 'PI', 22, 'piaui', 3212180);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (18, 'Paraná', 'PR', 41, 'parana', 11242720);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (19, 'Rio de Janeiro', 'RJ', 33, 'rio-de-janeiro', 16635996);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (20, 'Rio Grande do Norte', 'RN', 24, 'rio-grande-do-norte', 3474998);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (21, 'Rondônia', 'RO', 11, 'rondonia', 1787279);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (22, 'Roraima', 'RR', 14, 'roraima', 514229);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (23, 'Rio Grande do Sul', 'RS', 43, 'rio-grande-do-sul', 11286500);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (24, 'Santa Catarina', 'SC', 42, 'santa-catarina', 6910553);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (25, 'Sergipe', 'SE', 28, 'sergipe', 2265779);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (26, 'São Paulo', 'SP', 35, 'sao-paulo', 44749699);
INSERT INTO states (id, title, letter, iso, slug, population) VALUES (27, 'Tocantins', 'TO', 17, 'tocantins', 1532902);